# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ac2b1071e3ecebc22cf6e6f65316ddad505f6965c2c04e0376b745ddfae5fb1c2bc30ab8ce8e201710cac29e1923c87f86f2c629eddb4aa891ec9981022a332

test:
  secret_key_base: e6f09ff657e3fb83a78c0630170b45cb8114077e5a4afc8b64607ca9230725106ccd74022591755d060dac237fcb572cfd640e99224b1345a119a1b3e179b20f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
